config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/auth/facebook/callback' => 'sessions#create'

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'

  # resources :users do #, only: [:new, :create, :edit, :update, :show]
  #   resources :workers, only: [:new]
  #   resources :apps, only: [:index, :new, :create]
  # end

  # root 'welcome#home'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [:index, :create, :update, :show, :destroy], param: :slug do
        resources :todos, only: [:index, :create, :update, :show, :destroy] do
          # resources :user_todos, only: [:new, :create]
          get '/affectation/new' => 'todos#addWorker'
          post '/affectation' => 'todos#affectation'
        end
      end

      resources :users, only: [:index, :create, :update, :show, :destroy] do #, only: [:new, :create, :edit, :update, :show]
        # resources :workers, only: [:new]
      end
      resources :workers, only: [:index, :create, :update, :show, :destroy]

      post '/connect' => 'sessions#connect'
      # get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      post '/logout' => 'sessions#destroy'
      
      # get '/auth/facebook/callback' => 'sessions#create'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_one :worker
    has_secure_password
    validates_presence_of :name, :email, :password
    validates :email, uniqueness: true
    validates :name, format: { without: /[0-9]/, message: "does not allow numbers" }
    # validates_presence_of :worker, allow_nil: true
    has_many :created_projects, class_name: "Project", foreign_key: "created_by_id"
    has_many :created_todos, class_name: "Todo", foreign_key: "created_by_id"
    has_many :created_worker_todos, class_name: "WorkerTodo", foreign_key: "created_by_id"
    has_many :created_workers, class_name: "Worker", foreign_key: "created_by_id"
    has_many :updated_projects, class_name: "Project", foreign_key: "updated_by_id"
    has_many :updated_todos, class_name: "Todo", foreign_key: "updated_by_id"
    has_many :updated_worker_todos, class_name: "WorkerTodo", foreign_key: "updated_by_id"
    has_many :updated_workers, class_name: "Worker", foreign_key: "updated_by_id"
    scope :admins, -> { where(admin: true) }
    has_many :apps
    has_many :sessions

    def self.current_user
        @@current_user
    end

    def set_current_user
        @@current_user = self
    end

    def get_session(app)
        tokenPad = self.name + app.name + DateTime.now.to_s
        sha256 = Digest::SHA2.new(256)
        self.set_current_user
        app.set_current_app
        self.sessions.build(api_token: sha256.hexdigest(tokenPad), app: app).save!
        self.sessions.last
    end
    # u.attributes.merge({api_token: u.get_token(a)})
    # 1.day.from_now

    def check_session(token)
      self.sessions.find{|s| s.api_token == token}
    end
  
    def slug
      self.name.gsub(/\W/, '-')
    end
  
    def self.find_by_slug(slugified)
      self.find{|u| u.slug == slugified}
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_action :require_logged_in, only:[:show, :edit, :update]
  skip_before_action :authenticate_app_from_token!, only: [:index, :show, :update]
  skip_before_action :set_action_user, :authenticate_user_from_token!, only: [:create]

  def index
    @users = User.all

    render json: @users, status: :ok 
  end

  def show    
    @user = User.find(params[:id])
        unless @user.nil?
          render json: @user, status: :ok
        else
          render json: { error: 'User not found.' } 
        end
  end

  def create
    @user = User.create(user_params)
    # return redirect_to controller: 'users', action: 'new' unless @user.save
    
    if @user.valid?
        @user.save
        # @user.set_current_user
        session[:user_id] = @user.id
        render json: @user, status: :created
    else
        render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update    
    @user = User.find(params[:id])
    @user.update(user_params)

    
      if @user.save
        render json: @user, status: :created
      else
        render json: @user.errors, status: :unprocessable_entity 
      end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
#   before_action :require_logged_in, only:[:show, :edit, :update]
#   skip_before_action :set_action_user, only: [:create]

#   def index
#     @users = User.all

#     respond_to do |format|
#         if @users.empty?
#             format.html { redirect_to root_path, alert: 'Users is empty.' }                
#         else
#             format.html { render :index }
#         end
#         format.json { render json: @users, status: :ok }
#     end
#   end

#   def show    
#     @user = User.find(params[:id])
#     respond_to do |format|
#         unless @user.nil?
#             format.html { render :show }         
#         else
#             format.html { redirect_to users_path, alert: 'User not found.' }
#         end
#         format.json { render json: @user, status: :ok }
#     end  
#   end

#   def new
#     @user = User.new
#   end

#   def create
#     @user = User.new(user_params).set_current_user
#     # return redirect_to controller: 'users', action: 'new' unless @user.save

#     respond_to do |format|
#       if @user.valid?
#           @user.save
#           # @user.set_current_user
#           session[:user_id] = @user.id
#           format.html { redirect_to projects_path(@project), notice: 'User was successfully created.' }
#           format.json { render :show, status: :created, location: @user }                
#       else
#           format.html { render :new }
#           format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   def edit  
#     @user = User.find(params[:id])
#   end

#   def update    
#     @user = User.find(params[:id])
#     @user.update(user_params)

#     respond_to do |format|
#       if @user.save
#           format.html { redirect_to user_path(@user), notice: 'User was successfully updated.' }
#           format.json { render :show, status: :created, location: @user }
#       else
#           format.html { render :edit }
#           format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   private

#     def user_params
#       params.require(:user).permit(:name, :password, :email)
#     end
# end

app/views/users/_user.html.erb
<%= form_for @user, controller: 'users', action: 'create' do |f| %>
  <div class="fields_with_errors">
    <span class="error"><%= @user.errors.messages[:name].join(". ") if @user.errors.any? %></span>
    Username: <%= f.text_field :name %>
  </div>

  <div class="fields_with_errors">
    <span class="error"><%= @user.errors.messages[:email].join(". ") if @user.errors.any? %></span>
    Email: <%= f.text_field :email %>
  </div>

  <div class="fields_with_errors">
    <span class="error"><%= @user.errors.messages[:password].join(". ") if @user.errors.any? %></span>
    Password: <%= f.password_field :password %>
  </div>

  <%= f.submit "create" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'user', user: @user%>

<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<br>

<ul>
  <% @users.each do |u| %>
    <li><%= link_to u.name, user_path(u) %></li>
  <% end %>
</ul>

<%= link_to 'New User', new_user_path %> |
<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'user' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong><%= @user.name %></strong>  
</h1>

<p>
  <%= @user.email %>
</p>

<br><br>

<% if !@user.worker.nil? %>
  <h3>Duties as a Worker</h3>
  <br>

  <ul>
    <% @user.worker.todos.each do |t| %>
      <li><%= link_to t.task, project_todo_path(t.project.slug, t) %></li>
    <% end if @user.worker %>
  </ul>
<% end %>

<%= link_to 'Edit', user_path(@user) %> |
<% if @user.worker.nil? %> <%= link_to 'Become a Worker', new_user_worker_path(@user) %> | <% end %>
<%= link_to 'Back', users_path %>